### PR TITLE
Add "Authentication from environment"

### PR DESCRIPTION
**Pull request by alekseytomin**
I have to use the private nexus repository in gitlab-ci.
We use only authenticated access to it. But I mustn't write a password in scripts.

PS: I've chosen '@' as a symbol ('$' isn't possible in Kotlin). Maybe You will choose another one.

PPS: I have not found any other point to use environment variables.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Great suggestion. I would also never include credentials in scripts.

Indeed @ feels a bit odd. Maybe `{{MY_PW}}` could feel a bit more _templaty_?

I think before we should merge it, the fallback behaviour when a variable is not defined should be changed to make kscript stop script execution. Tis may clash with the rare cases that a pw is actually starting with {{ and ends with }}, but it seems preferable to be than using wrong credentials, just because the user forgot to `export` the variables in bash before invoking kscript.. What do you think?

**Comment by alekseytomin** [comment]
> Great suggestion. I would also never include credentials in scripts.
> 
> Indeed @ feels a bit odd. Maybe `{{MY_PW}}` could feel a bit more _templaty_?

Ok. I've forgotten this.

> I think before we should merge it, the fallback behaviour when a variable is not defined should be changed to make kscript stop script execution.

`System.getenv()` in Kotlin is a nonnull function.
Without any changes we have an exception:
```Exception in thread "main" java.lang.IllegalStateException: System.getenv(value.subs…ing(2, value.length - 2)) must not be null
	at kscript.app.DependencyUtilKt.decodeEnv(DependencyUtil.kt:72)
...
```
I think better to write something like
```Exception in thread "main" java.lang.RuntimeException: environment variable 'HEXUS_USER' doesn't found
	at kscript.app.DependencyUtilKt.decodeEnv(DependencyUtil.kt:76)
...
```

Or maybe hide the stacktrace?

**Comment by holgerbrandl** [comment]
3 minor aspects (which I typically would just do myself, but I'm a bit in a hurry this week)
1) In the docs the example pw artifactory_password should be uppercase ARTIFACTORY_PASSWORD since bash variable are typically uppercase
2) I like the more custom error. But the wording seems slightly wrong. Couldn't we just say

> "Could not resolve environment variable {{bla}} in maven repository credentials"

3) Instead of rethrowing the exception, we should better exit with 
```
errorMsg(lazyMessage().toString())
quit(1)
```
This will prefix the message with `[kscript] [ERROR]` which will help the user to distinguish script logic errors from kscript runtime errors.

**Comment by alekseytomin** [comment]
Done

**Comment by alekseytomin** [comment]
https://github.com/holgerbrandl/kscript/pull/248/commits/c8fc911e05009936e1697cc188a8794ff9dd4292
I've found than `System.getenv(key)` has a wrong type (`String!` instead of `String?`) and remove from code. `System.getenv()[key]` returns `String?`

**Comment by alekseytomin** [comment]
Is it okay?

**Comment by holgerbrandl** [comment]
Great PR, thanks for your support and patience. A release including your feature is planned for later today.

**Comment by alekseytomin** [comment]
Thanks!

**Pull request merged**
