### PR TITLE
Add installation instructions for Arch LInux

### PR DESCRIPTION
**Pull request by hanslovsky**
Super easy to install on arch linux

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Thanks for the PR. Did you add it to this repository? How can/will it be updated when we release a new version? Is this something we can/need to automate (see `kscript_release.sh`?

**Comment by mikroskeem** [comment]
Package in AUR updates as long as AUR package submitter is updating it.

**Comment by hanslovsky** [comment]
> Did you add it to this repository?

No, I just tried my luck installing through AUR and was lucky. I left a comment on the [kscript AUR package](https://aur.archlinux.org/packages/kscript/) asking the author to comment in here on this topic.

**Comment by holgerbrandl** [comment]
Thanks. It would be great to support arch-linux but we need to make sure that it stays in sync with our releases. Let's see what `pdz`'s opinion is

**Comment by dzieciolowski** [comment]
It should be easy to automate the AUR release process. For minor changes (no additional dependencies, etc.) all you have to do is to:

- register yourself on https://aur.archlinux.org/register/ and become a package maintainer/co-maintainer (one time only)
- git clone https://aur.archlinux.org/kscript.git
- update the PKGBUILD file/pkgver variable
- updpkgsums
- makepkg --printsrcinfo > .SRCINFO
- git add PKGBUILD .SRCINFO
- git commit
- git push

For complex changes you will have to tweak PKGBUILD file manually.

**Comment by holgerbrandl** [comment]
@dzieciolowski Could you include these build instructions into https://github.com/holgerbrandl/kscript/blob/master/misc/kscript_release.sh
? Similar how we do it for homebrew for instance.

I've registered an account "holgerbrandl" on AUR. As soon as we have release automation for AUR, I'll include it into my release routine.

**Comment by Prototik** [comment]
First of all `pdz` should add @holgerbrandl as co-maintainer (or transfer owner completely), further automation pretty easy.

**Comment by dzieciolowski** [comment]
Ownership of https://aur.archlinux.org/packages/kscript/ has been transfered to @holgerbrandl.

**Comment by Prototik** [comment]
Great, I'll prepare related code and instructions for @holgerbrandl a bit laterOn Jun 26, 2019 1:44 PM, Paweł Dzięciołowski <notifications@github.com> wrote:Ownership of https://aur.archlinux.org/packages/kscript/ has been transfered to @holgerbrandl.

**Comment by holgerbrandl** [comment]
Thanks, gentleman. I have received the ownership transfer info, and will merge the release automation bits once being provided by @Prototik

**Comment by holgerbrandl** [comment]
Any news @Prototik concerning some guidance about release automation for arch linux?

**Comment by mikroskeem** [comment]
Release automation? You mean something as simple as bumping the version?

Arch Linux `pacman-contrib` package provides `updpkgsums` command to automatically download new sources and update checksums array. Only thing you must do yourself is changing the version entry, however that can be automated as well using your own scripts.

**Comment by holgerbrandl** [comment]
I was referring to your last where you suggested that you potentially could prepare some code and instructions.

Essentially, what we would need are some programmatic bits (REST, some arch-linux-cli, etc) to be appended to https://github.com/holgerbrandl/kscript/blob/master/misc/kscript_release.sh
I honestly don't want to go to some web-interface manually each time when doing a release.

**Comment by mikroskeem** [comment]
Updating a package is as easy as `makepkg --printsrcinfo > .SRCINFO` after updating the PKGBUILD file, commiting changes and pushing to aur git repository. No need to interact with aurweb at all.




---- On Fri, 22 Nov 2019 11:11:01 +0000 notifications@github.com wrote ----



I was referring to your last where you suggested that you potentially could prepare some code and instructions.

Essentially, what we would need are some programmatic bits (REST, some arch-linux-cli, etc) to be appended to https://github.com/holgerbrandl/kscript/blob/master/misc/kscript_release.sh
I honestly don't want to go to some web-interface manually each time when doing a release.

**Comment by holgerbrandl** [comment]
Thanks for your help. I'll try to integrate it like that for the next release.

**Comment by holgerbrandl** [comment]
@mikroskeem I've added the archlinux releast bits to https://github.com/holgerbrandl/kscript/blob/master/misc/kscript_release.sh and pushed a new version https://aur.archlinux.org/packages/kscript/

Could you check if the release worked?

Unfortunately, I did not manage to install `makepkg` (could not find an ubuntu installer) and had to write the `.SRCINFO` manually.

**Comment by hanslovsky** [comment]
@holgerbrandl I just checked the AUR and I see version `2.9.0-1`:
```sh
$ yay -S kscript
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  kscript-2.9.0-1
```
but installation failed:
```
==> Making package: kscript 2.9.0-1 (Thu 12 Dec 2019 03:07:05 PM EST)
==> Retrieving sources...
  -> Downloading -.bin.zip...
Warning: The file name argument '-.bin.zip.part' looks like a flag.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://github.com/holgerbrandl//releases/download/v/--bin.zip
    Aborting...
```

These are the contents of `PKGBUILD`:
```
# Maintainer: Holger Brandl https://github.com/holgerbrandl/kscript/

pkgname=kscript
pkgver=2.9.0
pkgrel=1
pkgdesc='Enhanced scripting support for Kotlin on *nix-based systems'
arch=('any')
url='https://github.com/holgerbrandl/kscript'
license=('MIT')
depends=('kotlin')
source=("-.bin.zip::https://github.com/holgerbrandl//releases/download/v/--bin.zip")
sha256sums=('3d62b0db226566506a2531d765547595867230cd5d44dbedc65301cadfecdaaf')

package() {
    cd "/-/bin"

    install -Dm 755 kscript "/usr/bin/kscript"
    install -Dm 644 kscript.jar "/usr/bin/kscript.jar"
}
```
It seems that the `source` is not being composed correctly. I will have a look and see if I can find anything.

**Comment by hanslovsky** [comment]
What I found is that `${pkgname}` and `${pkgver}` are not being substituted with the values that are specified within the `cat - <<EOF` part. I also defined them outside and this seems to work:
```sh
kscript_version=123
archiveMd5=md5
pkgname=kscript
pkgver=${kscript_version}

cat - <<EOF

pkgname=$pkgname
pkgver=$pkgver
pkgrel=1
pkgdesc='Enhanced scripting support for Kotlin on *nix-based systems'
arch=('any')
url='https://github.com/holgerbrandl/kscript'
license=('MIT')
depends=('kotlin')
source=('${pkgname}-${pkgver}.bin.zip::https://github.com/holgerbrandl/${pkgname}/releases/download/v${pkgver}/${pkgname}-${pkgver}-bin.zip')
sha256sums=('${archiveMd5}')
package() {
    cd "${srcdir}/${pkgname}-${pkgver}/bin"
    install -Dm 755 kscript "${pkgdir}/usr/bin/kscript"
    install -Dm 644 kscript.jar "${pkgdir}/usr/bin/kscript.jar"
}
EOF

```

**Comment by mikroskeem** [comment]
I'll look into improving the situation this week.

**Pull request merged**
