### PR TITLE
Including scripts by relative reference - Fixes #303

### LINKED ISSUE #303: Including scripts by relative reference
I have seen issue #218 and from that ticket, it looks like the problem is already solved, but in my opinion, it's not, or at least not in all cases.

Please consider the following directory structure:
obraz

**service-script-a.kts** includes **common-script-a.kts**. But **common-script-a.kts** includes internally **common-script-b.kts**.
Now when I execute **service-script-a.kts** I get error: 

`[kscript] [ERROR] Failed to resolve //INCLUDE 'common-script-b.kts'
[[kscript] [ERROR] /home/vagrant/workspace/Kod/GitRepos/TestCase/service-a/common-script-b.kts (No such file or directory)]`

Fixing it shouldn't be difficult - it is enough to include files **always** relatively to the file which does the include. Without that, it is not possible to correctly structure scripts and encapsulate pieces of code.

I am attaching the above very simple test-case as a zip file.

[TestCase.zip](https://github.com/holgerbrandl/kscript/files/5921348/TestCase.zip)

### PR DESCRIPTION
**Pull request by aartiPl**
This patch Fixes #303 

I have tested it on my branch with URLs in the includes directory directed to my branch. After that, I have reverted them back to point to your master branch. Because of that, tests will not work on the branch, but only on the master.

I have started only Tests class in src/test directory. I am not sure how to start other tests. Please let me know if something else should be done to merge this PR.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Awesome. Thank you so much for supporting script!

I've run the test but they still seems to struggle with the PR:

Tests > test_include_annotations FAILED
    org.junit.ComparisonFailure: expected:<...ion
    fun url_included[_1() = println("i came from the internet")
    fun url_included_2() = println("i also] came from the inter...> but was:<...ion
    fun url_included[() = println("i] came from the inter...>
        at io.kotlintest.matchers.MatchersKt.shouldBe(Matchers.kt:15)
        at Tests.test_include_annotations(Tests.kt:212)

Tests > test_include_detection FAILED
    java.lang.AssertionError: expected: 2 but was: 1
        at io.kotlintest.matchers.MatchersKt.equalsError(Matchers.kt:89)
        at io.kotlintest.matchers.MatchersKt.shouldEqual(Matchers.kt:63)
        at io.kotlintest.matchers.MatchersKt.shouldBe(Matchers.kt:55)
        at Tests.test_include_detection(Tests.kt:220)

**Comment by aartiPl** [comment]
There is an inherent problem with testing changes covering resolving URLs on branches, at least in the current test setup. Test files rely on KScript Github *master* branch repository. But the problem is that if you make changes in test files on a branch, then those files are not yet in the *master* branch of the Github repo, so the tests will just fail.

In case of this PR, there is added a new script file, which is included by URL in test/resources/includes/rel_includes/include_by_url.kt. This new file is obviously not in the master branch, because PR is not yet merged, and that's why tests on the branch fail.

In such a case, to accomplish the tests on the PR branch you can do the following things:

1) Modify URLs to the test branch in files:
test/resources/includes/include_by_url.kt
test/resources/includes/include_variations.kts

For testing in my forked branch I have used the following URLs:
include_by_url.kt: @file:Include("https://raw.githubusercontent.com/aartiPl/kscript/Including_scripts_by_relative_reference_-_fixes_%23303/test/resources/includes/rel_includes/include_by_url.kt")
include_variations.kts: @file:Include("https://raw.githubusercontent.com/aartiPl/kscript/Including_scripts_by_relative_reference_-_fixes_%23303/test/resources/includes/include_by_url.kt")

2. Otherwise the tests can be run successfully only on the "master" branch, so only after the merge of PR.

**Comment by holgerbrandl** [comment]
Packaging seems indeed broken currently (see #324). 

I've run the tests locally against the PR and struggle to complete "kscript https://git.io/fxHBv" both on the terminal and from the IDE. This is because the file-suffix is no longer detected correctly. It must be kt but seems to be kts with PR. Am I missing something here?
Make sure to always wipe the cache before testing.

**Comment by aartiPl** [comment]
There is indeed something wrong with my implementation. I will try to figure out what's that and provide a fix. Thanks for your input!

**Comment by aartiPl** [comment]
Ok. I have managed to fix the problem. The remaining problems are with:

* packages - seems that they are broken anyway
* idea project - I can not test it as I am working in a virtual machine without UI

obraz
obraz

Please check if idea generated project is working as expected.

It seems to me that there would be needed some deeper refactoring in KScript. I have an idea how to do that. If you are willing to do such changes, I can work on it. But I prefer to do this after applying changes from this PR first.

**Comment by aartiPl** [comment]
Seems that the last broken use case is fixed now. There are failures only with packaging and idea. Can you please check those use cases?

**Comment by holgerbrandl** [comment]
Thank you so much @aartiPl  for your patience with my slow response times, and many thanks for your great support.

**Pull request merged**
