### PR TITLE
Support --idea with includes (#103)

### PR DESCRIPTION
**Pull request by EugeneSusla**
Caveat: only items declared in .kt files (not .kts) are picked up
by idea when resolving terms in its neighbours

Test:
- create a file that `//INCLUDE`s a relative .kt script, and a .kt url
- pass it to `kscript --idea` and ensure all terms from its includes are non-red
- execute it and ensure no compilation/runtime errors

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Imho the PR mixes `//include` management too much into the `Script` helper class, and the patch seemed a bit too complicated in my taste.

I've pushed a more simplistic fix into the branch https://github.com/holgerbrandl/kscript/tree/alternative_impl_pr105

What do you think about it?

The main functional difference is, that we actually need to resolve text mode and custom preamable in ant case, and if so use a temp-script in the `--idea` mode. Otherwise good code would be red, because preambles are not just methods but may also declare variables. And so does the text-processing mode. E.g. try/see the bundled test dsl with
```
/test/resources/custom_dsl/mydsl --idea test/resources/custom_dsl/mydsl_test_with_deps.kts
```

> Caveat: only items declared in .kt files (not .kts) are picked up
That's by design of Kotlin (and not related to kscript). `kts` scripts can not be used to include method definitions.

**Comment by EugeneSusla** [comment]
The simplified fix looks good, apart from the preambles treatment you bring up.

With regards to that - I'm not sure I understand your point why do we need to open temp script for the case with preambles/custom DSLs/text mode. I tried running:
`/test/resources/custom_dsl/mydsl --idea test/resources/custom_dsl/mydsl_test_with_deps.kts` against this patch, and it opens in IDE with zero red, including the `foo` reference (which I'm assuming is what you're referring to when you say there can also be variables, not just functions). With additional `-t` and `lines` usage, `mydsl_test_with_deps.kts` is still non-red. What ends up red is basically anything in the preambles that assumes to be part of a `.kts`, such as top-level code and `args` references, with the former being easy to circumvent with something like
```kotlin
val ignored = run {
    //your formerly-top-level code
}
```
This is still a lot better than just not being able to edit such scripts in IDE at all.

You can achieve the same in your patch as well if you pass `scriptResource` instead of `rawScript` to `launchIdeaWithKscriptlet`, and conditionally perpend `Script(correspondingPreambleStr.lines(), "kt").createTmpScript().toURL()` to its `includeURLs` parameter for custom preamble/text mode cases.

**Comment by holgerbrandl** [comment]
>>  I tried running against this patch
I think you're not running it correctly. `mydsl` is calling `kscript` internally, and I could imagine that it is not the devel version which is in your PATH? 

When using alternative_impl_pr105 it looks for me like

So no red code and the preamble is correctly inlined.

I've added another test in 9277610 to prevent regressions of this feature.

> Edit: I guess not pass scriptResource directly instead of rawScript, as that wouldn't handle urls/stdin, but rather move the preamble-appending part from prepareScript to postProcessScript, and use the latter in place of resolveIncludes

From what I can see there should not be any situation in which  a script that runs with `kscript` has red code in temp projects created using `--idea`. Could you provide a counter-example?

**Comment by holgerbrandl** [comment]
We could potentially wrap the resolved dsl preamble with some comment marker to make it more clear to the user how the temp script emerged. Mockup

```kotlin
// DSL_PREAMBLE START
fun include_1() = println("include_1")
// DSL_PREAMBLE END

include_1()
```

Furthermore we could even think about adding a small README.md to temp-projects detailing out the symlinking scheme. At the moment even if all code is green, users might be a bit lost. It could also not that for temp scripts, changes need to be synced back manually into the original source.

**Comment by EugeneSusla** [comment]
> I think you're not running it correctly. mydsl is calling kscript internally, and I could imagine that it is not the devel version which is in your PATH? Also make sure to use branch alternative_impl_pr105.

I meant to say that I ran it against my local branch with my patch. I made kscript in my path point to the dev version as well, so I'm confident I'm running the dev version.
The result I get is a project that achieves *both* no red and symlink to the actual script instead of a temp. That is the ideal outcome.

The main problem with resolving things is not the red code (of which you're right, there isn't) but that it doesn't let user modify the actual script, and instead duplicates the code to a temporary one, which defeats the purpose of using --idea in the first place

**Comment by holgerbrandl** [comment]
> The result I get is a project that achieves both no red and symlink to the actual script instead of a temp. That is the ideal outcome.

Indeed that the ideal outcome. Without using includes or preambles this is already the case now. In case of methods or symbols it would indeed be possible to use temp-files for preambles and symlink  these plus the original user script. i've played with such an implementation as well, but ran into problems if the preamble contains import statements. For example in the text processing mode (which in fact is just a built-in custom dsl mode), the preamble is:
```kotlin
 //DEPS com.github.holgerbrandl:kscript-support:1.2.4
import kscript.text.*
val lines = resolveArgFile(args)
```
Putting this into a sym-linked tempfile instead of actually resolving the include will result in red code when running e.g.
```bash
kscript --idea -t "lines.print()"
```
I could imagine import statements in preambles (but potentially also in includes) to be a common use-case. So consequently one might need to resolve not only the preambles but also the includes for `--idea`.

**Comment by holgerbrandl** [comment]
All right, let's do it this way then. I've adjusted the feature branch and merged it into master. I'm closing this PR, thanks a lot for input and the nice discussion.

**Pull request closed without merging**
