### PR TITLE
Package script with custom gradle

### PR DESCRIPTION
**Pull request by elihart**
Addresses https://github.com/holgerbrandl/kscript/issues/223

I wasn't sure how to package and test the change though - let me know any suggestions for that.

Thanks!

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Will this support an actual path like `KSCRIPT_CUSTOM_GRADLE_NAME=/path/to/gradle'? In particular, I wonder if this plays along with the downstream `requireInPath`.

Wouldn't be a `KSCRIPT_CUSTOM_GRADLE` a better name for the parameter?

**Comment by elihart** [comment]
I don't know, how should I build the project to test it?

`KSCRIPT_CUSTOM_GRADLE` sounds fine to me

**Comment by elihart** [comment]
@holgerbrandl do I just `./gradlew jar` to get an executable to test with, or is there something more involved?

**Comment by holgerbrandl** [comment]
Sorry for the delay. `./gradlew assemble` is all you need to build it.

**Comment by elihart** [comment]
I've opted instead to just add `./gradlew` to the PATH

**Pull request closed without merging**
