### PR TITLE
Use https version of Bintray for dependency resolution

### PR DESCRIPTION
**Pull request by rossbacher**
Bintray does not support `http` anymore

### CODE REVIEW

**Comment by rossbacher** [comment]
This will fix https://github.com/holgerbrandl/kscript/issues/254

**Comment by ilanpillemer** [comment]
when will this merge in?

**Comment by kaustavj** [comment]
For now you can use:

@file:MavenRepository("jcenter","https://jcenter.bintray.com")

**Comment by ilanpillemer** [comment]
```
[kscript] Resolving dependencies...[kscript] [ERROR] Failed to lookup dependencies. Check dependency locators or file a bug on https://github.com/holgerbrandl/kscript
[kscript] The error reported by maven was:
[kscript] [mvn] [INFO] Scanning for projects...
[kscript] [mvn] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[kscript] [mvn] [ERROR] 'repositories.repository.id' must be unique: jcenter -> http://jcenter.bintray.com/ vs https://jcenter.bintray.com @ line 20, column 17
[kscript] [mvn]  @ 
[kscript] [mvn] [ERROR] The build could not read 1 project -> [Help 1]
[kscript] [mvn] [ERROR]   
[kscript] [mvn] [ERROR]   The project kscript:maven_template:1.0 (/tmp/__resdeps__temp__2902151751028993012_pom.xml) has 1 error
[kscript] [mvn] [ERROR]     'repositories.repository.id' must be unique: jcenter -> http://jcenter.bintray.com/ vs https://jcenter.bintray.com @ line 20, column 17
[kscript] [mvn] [ERROR] 
[kscript] [mvn] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[kscript] [mvn] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[kscript] [mvn] [ERROR] 
[kscript] [mvn] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[kscript] [mvn] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[kscript] [mvn] 
[kscript] Generated pom file was:
```

That didn't work.. 😢

**Comment by holgerbrandl** [comment]
I'll test it later today, and if test are fine, I hope to merge it tonight.

**Comment by ilanpillemer** [comment]
Hi, any updates on when this should be tested and merged?

**Comment by holgerbrandl** [comment]
Thanks for your help and contribution. I'll release a new version tonight.

@ilanpillemer I've not yet backported fixes to old releases of kscript. What's stopping you from using the latest version?

**Comment by ilanpillemer** [comment]
Latest version might work. I use docker images that use quite an older version. Once the new version is released I can update the docker images and rebuild and redeploy to Kubernetes. If the latest version works with scripts written for much older versions then I won't need backport.

**Comment by twyatt** [comment]
Thanks for the quick turnaround, `2.9.3` fixed retrieving dependencies from Bintray for me.

**Pull request merged**
